package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CurGrupCours generated by hbm2java
 */
@Entity
@Table(name = "cur_grup_cours", catalog = "proj_col")
public class CurGrupCours implements java.io.Serializable {

	private CurGrupCoursId id;
	private CurCourse curCourse;
	private CurGrup curGrup;
	private int ncredits;

	public CurGrupCours() {
	}

	public CurGrupCours(CurGrupCoursId id, CurCourse curCourse,
			CurGrup curGrup, int ncredits) {
		this.id = id;
		this.curCourse = curCourse;
		this.curGrup = curGrup;
		this.ncredits = ncredits;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "groupid", column = @Column(name = "groupid", nullable = false)),
			@AttributeOverride(name = "courseid", column = @Column(name = "courseid", nullable = false)) })
	public CurGrupCoursId getId() {
		return this.id;
	}

	public void setId(CurGrupCoursId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseid", nullable = false, insertable = false, updatable = false)
	public CurCourse getCurCourse() {
		return this.curCourse;
	}

	public void setCurCourse(CurCourse curCourse) {
		this.curCourse = curCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "groupid", nullable = false, insertable = false, updatable = false)
	public CurGrup getCurGrup() {
		return this.curGrup;
	}

	public void setCurGrup(CurGrup curGrup) {
		this.curGrup = curGrup;
	}

	@Column(name = "ncredits", nullable = false)
	public int getNcredits() {
		return this.ncredits;
	}

	public void setNcredits(int ncredits) {
		this.ncredits = ncredits;
	}

}
