package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CurGrupCoursId generated by hbm2java
 */
@Embeddable
public class CurGrupCoursId implements java.io.Serializable {

	private int groupid;
	private int courseid;

	public CurGrupCoursId() {
	}

	public CurGrupCoursId(int groupid, int courseid) {
		this.groupid = groupid;
		this.courseid = courseid;
	}

	@Column(name = "groupid", nullable = false)
	public int getGroupid() {
		return this.groupid;
	}

	public void setGroupid(int groupid) {
		this.groupid = groupid;
	}

	@Column(name = "courseid", nullable = false)
	public int getCourseid() {
		return this.courseid;
	}

	public void setCourseid(int courseid) {
		this.courseid = courseid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CurGrupCoursId))
			return false;
		CurGrupCoursId castOther = (CurGrupCoursId) other;

		return (this.getGroupid() == castOther.getGroupid())
				&& (this.getCourseid() == castOther.getCourseid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getGroupid();
		result = 37 * result + this.getCourseid();
		return result;
	}

}
