package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "proj_col")
public class Resource implements java.io.Serializable {

	private int id;
	private String fileName;
	private String wikitext;
	private String type;
	private Set<CurCourse> curCourses = new HashSet<CurCourse>(0);

	public Resource() {
	}

	public Resource(int id) {
		this.id = id;
	}

	public Resource(int id, String fileName, String wikitext, String type,
			Set<CurCourse> curCourses) {
		this.id = id;
		this.fileName = fileName;
		this.wikitext = wikitext;
		this.type = type;
		this.curCourses = curCourses;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "file_name", length = 45)
	public String getFileName() {
		return this.fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	@Column(name = "wikitext", length = 65535)
	public String getWikitext() {
		return this.wikitext;
	}

	public void setWikitext(String wikitext) {
		this.wikitext = wikitext;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resource")
	public Set<CurCourse> getCurCourses() {
		return this.curCourses;
	}

	public void setCurCourses(Set<CurCourse> curCourses) {
		this.curCourses = curCourses;
	}

}
