package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContracteStudiuId generated by hbm2java
 */
@Embeddable
public class ContracteStudiuId implements java.io.Serializable {

	private int nrmat;
	private int idCurs;
	private int contractVersion;

	public ContracteStudiuId() {
	}

	public ContracteStudiuId(int nrmat, int idCurs, int contractVersion) {
		this.nrmat = nrmat;
		this.idCurs = idCurs;
		this.contractVersion = contractVersion;
	}

	@Column(name = "nrmat", nullable = false)
	public int getNrmat() {
		return this.nrmat;
	}

	public void setNrmat(int nrmat) {
		this.nrmat = nrmat;
	}

	@Column(name = "id_curs", nullable = false)
	public int getIdCurs() {
		return this.idCurs;
	}

	public void setIdCurs(int idCurs) {
		this.idCurs = idCurs;
	}

	@Column(name = "contract_version", nullable = false)
	public int getContractVersion() {
		return this.contractVersion;
	}

	public void setContractVersion(int contractVersion) {
		this.contractVersion = contractVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContracteStudiuId))
			return false;
		ContracteStudiuId castOther = (ContracteStudiuId) other;

		return (this.getNrmat() == castOther.getNrmat())
				&& (this.getIdCurs() == castOther.getIdCurs())
				&& (this.getContractVersion() == castOther.getContractVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNrmat();
		result = 37 * result + this.getIdCurs();
		result = 37 * result + this.getContractVersion();
		return result;
	}

}
