package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * MsgChannel generated by hbm2java
 */
@Entity
@Table(name = "msg_channel")
public class MsgChannel implements java.io.Serializable {

	private String id;
	private Set<Users> userses = new HashSet<Users>(0);
	private Set<MsgMessage> msgMessages = new HashSet<MsgMessage>(0);

	public MsgChannel() {
	}

	public MsgChannel(String id) {
		this.id = id;
	}

	public MsgChannel(String id, Set<Users> userses, Set<MsgMessage> msgMessages) {
		this.id = id;
		this.userses = userses;
		this.msgMessages = msgMessages;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 45)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "msg_subscription", joinColumns = { @JoinColumn(name = "chanid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "login", nullable = false, updatable = false) })
	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "msg_message_channel", joinColumns = { @JoinColumn(name = "chanid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "msgid", nullable = false, updatable = false) })
	public Set<MsgMessage> getMsgMessages() {
		return this.msgMessages;
	}

	public void setMsgMessages(Set<MsgMessage> msgMessages) {
		this.msgMessages = msgMessages;
	}

}
