package pcol.server.domain;

// Generated May 15, 2011 7:09:00 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * NotePartiale generated by hbm2java
 */
@Entity
@Table(name = "note_partiale", catalog = "proj_col")
public class NotePartiale implements java.io.Serializable {

	private int nrmatr;
	private SchemaNotare schemaNotare;
	private Studenti studenti;
	private float valoare;

	public NotePartiale() {
	}

	public NotePartiale(SchemaNotare schemaNotare, Studenti studenti,
			float valoare) {
		this.schemaNotare = schemaNotare;
		this.studenti = studenti;
		this.valoare = valoare;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "studenti"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "nrmatr", unique = true, nullable = false)
	public int getNrmatr() {
		return this.nrmatr;
	}

	public void setNrmatr(int nrmatr) {
		this.nrmatr = nrmatr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "schemaId", nullable = false)
	public SchemaNotare getSchemaNotare() {
		return this.schemaNotare;
	}

	public void setSchemaNotare(SchemaNotare schemaNotare) {
		this.schemaNotare = schemaNotare;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Studenti getStudenti() {
		return this.studenti;
	}

	public void setStudenti(Studenti studenti) {
		this.studenti = studenti;
	}

	@Column(name = "valoare", nullable = false, precision = 12, scale = 0)
	public float getValoare() {
		return this.valoare;
	}

	public void setValoare(float valoare) {
		this.valoare = valoare;
	}

}
