package pcol.server.domain;
// Generated Mar 13, 2011 10:37:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CuriculeId generated by hbm2java
 */
@Embeddable
public class CuriculeId  implements java.io.Serializable {


     private int curs;
     private int sectie;

    public CuriculeId() {
    }

    public CuriculeId(int curs, int sectie) {
       this.curs = curs;
       this.sectie = sectie;
    }
   

    @Column(name="curs", nullable=false)
    public int getCurs() {
        return this.curs;
    }
    
    public void setCurs(int curs) {
        this.curs = curs;
    }

    @Column(name="sectie", nullable=false)
    public int getSectie() {
        return this.sectie;
    }
    
    public void setSectie(int sectie) {
        this.sectie = sectie;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CuriculeId) ) return false;
		 CuriculeId castOther = ( CuriculeId ) other; 
         
		 return (this.getCurs()==castOther.getCurs())
 && (this.getSectie()==castOther.getSectie());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurs();
         result = 37 * result + this.getSectie();
         return result;
   }   


}


