package pcol.server.domain;
// Generated Mar 13, 2011 10:37:29 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Studenti generated by hbm2java
 */
@Entity
@Table(name="studenti"
    ,catalog="proj_col"
)
public class Studenti  implements java.io.Serializable {


     private Integer id;
     private int version;
     private Persoane persoane;
     private Sectii sectii;
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<ContracteStudiu> contracteStudius = new HashSet<ContracteStudiu>(0);

    public Studenti() {
    }

	
    public Studenti(Persoane persoane, Sectii sectii) {
        this.persoane = persoane;
        this.sectii = sectii;
    }
    public Studenti(Persoane persoane, Sectii sectii, Set<Users> userses, Set<ContracteStudiu> contracteStudius) {
       this.persoane = persoane;
       this.sectii = sectii;
       this.userses = userses;
       this.contracteStudius = contracteStudius;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_pers", nullable=false)
    public Persoane getPersoane() {
        return this.persoane;
    }
    
    public void setPersoane(Persoane persoane) {
        this.persoane = persoane;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sectieId", nullable=false)
    public Sectii getSectii() {
        return this.sectii;
    }
    
    public void setSectii(Sectii sectii) {
        this.sectii = sectii;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentis")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studenti")
    public Set<ContracteStudiu> getContracteStudius() {
        return this.contracteStudius;
    }
    
    public void setContracteStudius(Set<ContracteStudiu> contracteStudius) {
        this.contracteStudius = contracteStudius;
    }




}


