package pcol.server.domain;
// Generated Mar 13, 2011 10:37:29 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Curicule generated by hbm2java
 */
@Entity
@Table(name="curicule"
    ,catalog="proj_col"
)
public class Curicule  implements java.io.Serializable {


     private CuriculeId id;
     private Cursuri cursuri;
     private Sectii sectii;
     private int semestru;
     private int credite;
     private String tip;

    public Curicule() {
    }

    public Curicule(CuriculeId id, Cursuri cursuri, Sectii sectii, int semestru, int credite, String tip) {
       this.id = id;
       this.cursuri = cursuri;
       this.sectii = sectii;
       this.semestru = semestru;
       this.credite = credite;
       this.tip = tip;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="curs", column=@Column(name="curs", nullable=false) ), 
        @AttributeOverride(name="sectie", column=@Column(name="sectie", nullable=false) ) } )
    public CuriculeId getId() {
        return this.id;
    }
    
    public void setId(CuriculeId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curs", nullable=false, insertable=false, updatable=false)
    public Cursuri getCursuri() {
        return this.cursuri;
    }
    
    public void setCursuri(Cursuri cursuri) {
        this.cursuri = cursuri;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sectie", nullable=false, insertable=false, updatable=false)
    public Sectii getSectii() {
        return this.sectii;
    }
    
    public void setSectii(Sectii sectii) {
        this.sectii = sectii;
    }
    
    @Column(name="semestru", nullable=false)
    public int getSemestru() {
        return this.semestru;
    }
    
    public void setSemestru(int semestru) {
        this.semestru = semestru;
    }
    
    @Column(name="credite", nullable=false)
    public int getCredite() {
        return this.credite;
    }
    
    public void setCredite(int credite) {
        this.credite = credite;
    }
    
    @Column(name="tip", nullable=false, length=15)
    public String getTip() {
        return this.tip;
    }
    
    public void setTip(String tip) {
        this.tip = tip;
    }




}


