package pcol.server.domain;
// Generated Mar 13, 2011 10:37:29 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="proj_col"
)
public class Users  implements java.io.Serializable {


     private String loginName;
     private String passwordHash;
     private String salt;
     private String lastlogin;
     private String lastip;
     private Set<Studenti> studentis = new HashSet<Studenti>(0);

    public Users() {
    }

	
    public Users(String loginName, String passwordHash, String salt) {
        this.loginName = loginName;
        this.passwordHash = passwordHash;
        this.salt = salt;
    }
    public Users(String loginName, String passwordHash, String salt, String lastlogin, String lastip, Set<Studenti> studentis) {
       this.loginName = loginName;
       this.passwordHash = passwordHash;
       this.salt = salt;
       this.lastlogin = lastlogin;
       this.lastip = lastip;
       this.studentis = studentis;
    }
   
     @Id 
    
    @Column(name="login_name", unique=true, nullable=false, length=45)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
    
    @Column(name="password_hash", nullable=false, length=45)
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    
    @Column(name="salt", nullable=false, length=45)
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    
    @Column(name="lastlogin", length=45)
    public String getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(String lastlogin) {
        this.lastlogin = lastlogin;
    }
    
    @Column(name="lastip", length=45)
    public String getLastip() {
        return this.lastip;
    }
    
    public void setLastip(String lastip) {
        this.lastip = lastip;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="conturi_studenti", catalog="proj_col", uniqueConstraints=@UniqueConstraint(columnNames="id_student"), joinColumns = { 
        @JoinColumn(name="login_name", unique=true, nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_student", unique=true, nullable=false, updatable=false) })
    public Set<Studenti> getStudentis() {
        return this.studentis;
    }
    
    public void setStudentis(Set<Studenti> studentis) {
        this.studentis = studentis;
    }




}


