package pcol.server.domain;

// Generated May 19, 2011 4:58:35 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teme generated by hbm2java
 */
@Entity
@Table(name = "teme", catalog = "proj_col")
public class Teme implements java.io.Serializable {

	private Integer id;
	private Resource resource;
	private CurCourse curCourse;
	private Date deadline;
	private Set<TmStudent> tmStudents = new HashSet<TmStudent>(0);

	public Teme() {
	}

	public Teme(Resource resource, CurCourse curCourse) {
		this.resource = resource;
		this.curCourse = curCourse;
	}

	public Teme(Resource resource, CurCourse curCourse, Date deadline,
			Set<TmStudent> tmStudents) {
		this.resource = resource;
		this.curCourse = curCourse;
		this.deadline = deadline;
		this.tmStudents = tmStudents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "resourceId", nullable = false)
	public Resource getResource() {
		return this.resource;
	}

	public void setResource(Resource resource) {
		this.resource = resource;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "curs", nullable = false)
	public CurCourse getCurCourse() {
		return this.curCourse;
	}

	public void setCurCourse(CurCourse curCourse) {
		this.curCourse = curCourse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deadline", length = 19)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teme")
	public Set<TmStudent> getTmStudents() {
		return this.tmStudents;
	}

	public void setTmStudents(Set<TmStudent> tmStudents) {
		this.tmStudents = tmStudents;
	}

}
