package pcol.server.domain;
// Generated Apr 14, 2011 10:54:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Facultati generated by hbm2java
 */
@Entity
@Table(name="facultati"
    ,catalog="proj_col"
)
public class Facultati  implements java.io.Serializable {


     private Integer id;
     private int version;
     private String nume;
     private Set<Sectii> sectiis = new HashSet<Sectii>(0);

    public Facultati() {
    }

	
    public Facultati(String nume) {
        this.nume = nume;
    }
    public Facultati(String nume, Set<Sectii> sectiis) {
       this.nume = nume;
       this.sectiis = sectiis;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
    
    @Column(name="nume", nullable=false, length=45)
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="facultati")
    public Set<Sectii> getSectiis() {
        return this.sectiis;
    }
    
    public void setSectiis(Set<Sectii> sectiis) {
        this.sectiis = sectiis;
    }




}


