package pcol.server.domain;

// Generated Apr 28, 2011 8:02:06 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Logins generated by hbm2java
 */
@Entity
@Table(name = "logins", catalog = "proj_col")
public class Logins implements java.io.Serializable {

	private String loginName;
	private Persoane persoane;
	private String passwordHash;
	private String salt;
	private String lastlogin;
	private String lastip;
	private Set<Profesori> profesoris = new HashSet<Profesori>(0);
	private Set<MsgMessage> msgMessages = new HashSet<MsgMessage>(0);
	private Set<MsgChannel> msgChannels = new HashSet<MsgChannel>(0);
	private Set<Studenti> studentis = new HashSet<Studenti>(0);

	public Logins() {
	}

	public Logins(String loginName, String passwordHash, String salt) {
		this.loginName = loginName;
		this.passwordHash = passwordHash;
		this.salt = salt;
	}

	public Logins(String loginName, Persoane persoane, String passwordHash,
			String salt, String lastlogin, String lastip,
			Set<Profesori> profesoris, Set<MsgMessage> msgMessages,
			Set<MsgChannel> msgChannels, Set<Studenti> studentis) {
		this.loginName = loginName;
		this.persoane = persoane;
		this.passwordHash = passwordHash;
		this.salt = salt;
		this.lastlogin = lastlogin;
		this.lastip = lastip;
		this.profesoris = profesoris;
		this.msgMessages = msgMessages;
		this.msgChannels = msgChannels;
		this.studentis = studentis;
	}

	@Id
	@Column(name = "login_name", unique = true, nullable = false, length = 45)
	public String getLoginName() {
		return this.loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "persoana")
	public Persoane getPersoane() {
		return this.persoane;
	}

	public void setPersoane(Persoane persoane) {
		this.persoane = persoane;
	}

	@Column(name = "password_hash", nullable = false, length = 45)
	public String getPasswordHash() {
		return this.passwordHash;
	}

	public void setPasswordHash(String passwordHash) {
		this.passwordHash = passwordHash;
	}

	@Column(name = "salt", nullable = false, length = 45)
	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}

	@Column(name = "lastlogin", length = 45)
	public String getLastlogin() {
		return this.lastlogin;
	}

	public void setLastlogin(String lastlogin) {
		this.lastlogin = lastlogin;
	}

	@Column(name = "lastip", length = 45)
	public String getLastip() {
		return this.lastip;
	}

	public void setLastip(String lastip) {
		this.lastip = lastip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logins")
	public Set<Profesori> getProfesoris() {
		return this.profesoris;
	}

	public void setProfesoris(Set<Profesori> profesoris) {
		this.profesoris = profesoris;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logins")
	public Set<MsgMessage> getMsgMessages() {
		return this.msgMessages;
	}

	public void setMsgMessages(Set<MsgMessage> msgMessages) {
		this.msgMessages = msgMessages;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "msg_subscription", catalog = "proj_col", joinColumns = { @JoinColumn(name = "login", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "chanid", nullable = false, updatable = false) })
	public Set<MsgChannel> getMsgChannels() {
		return this.msgChannels;
	}

	public void setMsgChannels(Set<MsgChannel> msgChannels) {
		this.msgChannels = msgChannels;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "logins")
	public Set<Studenti> getStudentis() {
		return this.studentis;
	}

	public void setStudentis(Set<Studenti> studentis) {
		this.studentis = studentis;
	}

}
