package pcol.server.domain;

// Generated Apr 28, 2011 8:02:06 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsgMessage generated by hbm2java
 */
@Entity
@Table(name = "msg_message", catalog = "proj_col")
public class MsgMessage implements java.io.Serializable {

	private Integer id;
	private Logins logins;
	private String msg;
	private String level;
	private Date date;
	private Set<MsgChannel> msgChannels = new HashSet<MsgChannel>(0);

	public MsgMessage() {
	}

	public MsgMessage(Logins logins, String msg, String level, Date date) {
		this.logins = logins;
		this.msg = msg;
		this.level = level;
		this.date = date;
	}

	public MsgMessage(Logins logins, String msg, String level, Date date,
			Set<MsgChannel> msgChannels) {
		this.logins = logins;
		this.msg = msg;
		this.level = level;
		this.date = date;
		this.msgChannels = msgChannels;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "expeditor", nullable = false)
	public Logins getLogins() {
		return this.logins;
	}

	public void setLogins(Logins logins) {
		this.logins = logins;
	}

	@Column(name = "msg", nullable = false, length = 65535)
	public String getMsg() {
		return this.msg;
	}

	public void setMsg(String msg) {
		this.msg = msg;
	}

	@Column(name = "level", nullable = false, length = 10)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "msg_message_channel", catalog = "proj_col", joinColumns = { @JoinColumn(name = "msgid", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "chanid", nullable = false, updatable = false) })
	public Set<MsgChannel> getMsgChannels() {
		return this.msgChannels;
	}

	public void setMsgChannels(Set<MsgChannel> msgChannels) {
		this.msgChannels = msgChannels;
	}

}
