package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgFaculty generated by hbm2java
 */
@Entity
@Table(name = "org_faculty", catalog = "proj_col")
public class OrgFaculty implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<OrgSection> orgSections = new HashSet<OrgSection>(0);

	public OrgFaculty() {
	}

	public OrgFaculty(String name) {
		this.name = name;
	}

	public OrgFaculty(String name, Set<OrgSection> orgSections) {
		this.name = name;
		this.orgSections = orgSections;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgFaculty")
	public Set<OrgSection> getOrgSections() {
		return this.orgSections;
	}

	public void setOrgSections(Set<OrgSection> orgSections) {
		this.orgSections = orgSections;
	}

}
