package pcol.server.domain;

// Generated Apr 28, 2011 8:02:06 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OrgSection generated by hbm2java
 */
@Entity
@Table(name = "org_section", catalog = "proj_col")
public class OrgSection implements java.io.Serializable {

	private Integer id;
	private OrgFaculty orgFaculty;
	private String name;
	private Set<Curicul> curiculs = new HashSet<Curicul>(0);
	private Set<OrgGroup> orgGroups = new HashSet<OrgGroup>(0);

	public OrgSection() {
	}

	public OrgSection(OrgFaculty orgFaculty, String name) {
		this.orgFaculty = orgFaculty;
		this.name = name;
	}

	public OrgSection(OrgFaculty orgFaculty, String name,
			Set<Curicul> curiculs, Set<OrgGroup> orgGroups) {
		this.orgFaculty = orgFaculty;
		this.name = name;
		this.curiculs = curiculs;
		this.orgGroups = orgGroups;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "faculty", nullable = false)
	public OrgFaculty getOrgFaculty() {
		return this.orgFaculty;
	}

	public void setOrgFaculty(OrgFaculty orgFaculty) {
		this.orgFaculty = orgFaculty;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgSection")
	public Set<Curicul> getCuriculs() {
		return this.curiculs;
	}

	public void setCuriculs(Set<Curicul> curiculs) {
		this.curiculs = curiculs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgSection")
	public Set<OrgGroup> getOrgGroups() {
		return this.orgGroups;
	}

	public void setOrgGroups(Set<OrgGroup> orgGroups) {
		this.orgGroups = orgGroups;
	}

}
