package pcol.server.domain;

// Generated May 17, 2011 11:37:48 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Resource generated by hbm2java
 */
@Entity
@Table(name = "resource", catalog = "proj_col", uniqueConstraints = @UniqueConstraint(columnNames = "numefisier"))
public class Resource implements java.io.Serializable {

	private Integer id;
	private CurCourse curCourse;
	private String numefisier;
	private String descriere;

	public Resource() {
	}

	public Resource(String numefisier, String descriere) {
		this.numefisier = numefisier;
		this.descriere = descriere;
	}

	public Resource(CurCourse curCourse, String numefisier, String descriere) {
		this.curCourse = curCourse;
		this.numefisier = numefisier;
		this.descriere = descriere;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "couseId")
	public CurCourse getCurCourse() {
		return this.curCourse;
	}

	public void setCurCourse(CurCourse curCourse) {
		this.curCourse = curCourse;
	}

	@Column(name = "numefisier", unique = true, nullable = false)
	public String getNumefisier() {
		return this.numefisier;
	}

	public void setNumefisier(String numefisier) {
		this.numefisier = numefisier;
	}

	@Column(name = "descriere", nullable = false, length = 45)
	public String getDescriere() {
		return this.descriere;
	}

	public void setDescriere(String descriere) {
		this.descriere = descriere;
	}

}
