package pcol.server.domain;
// Generated Apr 14, 2011 10:54:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resurse generated by hbm2java
 */
@Entity
@Table(name="resurse"
    ,catalog="proj_col"
)
public class Resurse  implements java.io.Serializable {


     private int id;
     private String fileName;
     private String wikitext;
     private String type;
     private Set<Cursuri> cursuris = new HashSet<Cursuri>(0);

    public Resurse() {
    }

	
    public Resurse(int id) {
        this.id = id;
    }
    public Resurse(int id, String fileName, String wikitext, String type, Set<Cursuri> cursuris) {
       this.id = id;
       this.fileName = fileName;
       this.wikitext = wikitext;
       this.type = type;
       this.cursuris = cursuris;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="file_name", length=45)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }
    
    @Column(name="wikitext", length=65535)
    public String getWikitext() {
        return this.wikitext;
    }
    
    public void setWikitext(String wikitext) {
        this.wikitext = wikitext;
    }
    
    @Column(name="type", length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="resurse")
    public Set<Cursuri> getCursuris() {
        return this.cursuris;
    }
    
    public void setCursuris(Set<Cursuri> cursuris) {
        this.cursuris = cursuris;
    }




}


