package pcol.server.domain;
// Generated Apr 15, 2011 12:35:22 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Sectii generated by hbm2java
 */
@Entity
@Table(name="sectii"
    ,catalog="proj_col"
)
public class Sectii  implements java.io.Serializable {


     private Integer id;
     private int version;
     private Facultati facultati;
     private String nume;
     private Set<Curicule> curicules = new HashSet<Curicule>(0);
     private Set<Grupe> grupes = new HashSet<Grupe>(0);

    public Sectii() {
    }

	
    public Sectii(Facultati facultati, String nume) {
        this.facultati = facultati;
        this.nume = nume;
    }
    public Sectii(Facultati facultati, String nume, Set<Curicule> curicules, Set<Grupe> grupes) {
       this.facultati = facultati;
       this.nume = nume;
       this.curicules = curicules;
       this.grupes = grupes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="facultate", nullable=false)
    public Facultati getFacultati() {
        return this.facultati;
    }
    
    public void setFacultati(Facultati facultati) {
        this.facultati = facultati;
    }
    
    @Column(name="nume", nullable=false, length=45)
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sectii")
    public Set<Curicule> getCuricules() {
        return this.curicules;
    }
    
    public void setCuricules(Set<Curicule> curicules) {
        this.curicules = curicules;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="sectii")
    public Set<Grupe> getGrupes() {
        return this.grupes;
    }
    
    public void setGrupes(Set<Grupe> grupes) {
        this.grupes = grupes;
    }




}


