package pcol.server.domain;

// Generated May 17, 2011 11:37:48 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Teme generated by hbm2java
 */
@Entity
@Table(name = "teme", catalog = "proj_col")
public class Teme implements java.io.Serializable {

	private int id;
	private CurCourse curCourse;
	private int resourceId;
	private String descriere;
	private Date deadline;
	private Set<TmStudent> tmStudents = new HashSet<TmStudent>(0);

	public Teme() {
	}

	public Teme(int id, CurCourse curCourse, int resourceId, String descriere) {
		this.id = id;
		this.curCourse = curCourse;
		this.resourceId = resourceId;
		this.descriere = descriere;
	}

	public Teme(int id, CurCourse curCourse, int resourceId, String descriere,
			Date deadline, Set<TmStudent> tmStudents) {
		this.id = id;
		this.curCourse = curCourse;
		this.resourceId = resourceId;
		this.descriere = descriere;
		this.deadline = deadline;
		this.tmStudents = tmStudents;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "curs", nullable = false)
	public CurCourse getCurCourse() {
		return this.curCourse;
	}

	public void setCurCourse(CurCourse curCourse) {
		this.curCourse = curCourse;
	}

	@Column(name = "resourceId", nullable = false)
	public int getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(int resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "descriere", nullable = false, length = 45)
	public String getDescriere() {
		return this.descriere;
	}

	public void setDescriere(String descriere) {
		this.descriere = descriere;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deadline", length = 19)
	public Date getDeadline() {
		return this.deadline;
	}

	public void setDeadline(Date deadline) {
		this.deadline = deadline;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "teme")
	public Set<TmStudent> getTmStudents() {
		return this.tmStudents;
	}

	public void setTmStudents(Set<TmStudent> tmStudents) {
		this.tmStudents = tmStudents;
	}

}
