package pcol.server.domain;

// Generated May 15, 2011 7:09:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmStudent generated by hbm2java
 */
@Entity
@Table(name = "tm_student", catalog = "proj_col")
public class TmStudent implements java.io.Serializable {

	private TmStudentId id;
	private Teme teme;
	private Studenti studenti;
	private String status;
	private Date dataIncarcare;
	private String numeFisier;

	public TmStudent() {
	}

	public TmStudent(TmStudentId id, Teme teme, Studenti studenti,
			String status, Date dataIncarcare, String numeFisier) {
		this.id = id;
		this.teme = teme;
		this.studenti = studenti;
		this.status = status;
		this.dataIncarcare = dataIncarcare;
		this.numeFisier = numeFisier;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "temaId", column = @Column(name = "temaId", nullable = false)),
			@AttributeOverride(name = "nrmatr", column = @Column(name = "nrmatr", nullable = false)) })
	public TmStudentId getId() {
		return this.id;
	}

	public void setId(TmStudentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "temaId", nullable = false, insertable = false, updatable = false)
	public Teme getTeme() {
		return this.teme;
	}

	public void setTeme(Teme teme) {
		this.teme = teme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nrmatr", nullable = false, insertable = false, updatable = false)
	public Studenti getStudenti() {
		return this.studenti;
	}

	public void setStudenti(Studenti studenti) {
		this.studenti = studenti;
	}

	@Column(name = "status", nullable = false, length = 6)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_incarcare", nullable = false, length = 19)
	public Date getDataIncarcare() {
		return this.dataIncarcare;
	}

	public void setDataIncarcare(Date dataIncarcare) {
		this.dataIncarcare = dataIncarcare;
	}

	@Column(name = "nume_fisier", nullable = false)
	public String getNumeFisier() {
		return this.numeFisier;
	}

	public void setNumeFisier(String numeFisier) {
		this.numeFisier = numeFisier;
	}

}
