package pcol.server.domain;
// Generated Apr 14, 2011 10:54:13 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmStudent generated by hbm2java
 */
@Entity
@Table(name="tm_student"
    ,catalog="proj_col"
)
public class TmStudent  implements java.io.Serializable {


     private TmStudentId id;
     private Teme teme;
     private Studenti studenti;
     private String status;
     private Date deadline;

    public TmStudent() {
    }

	
    public TmStudent(TmStudentId id, Teme teme, Studenti studenti, String status) {
        this.id = id;
        this.teme = teme;
        this.studenti = studenti;
        this.status = status;
    }
    public TmStudent(TmStudentId id, Teme teme, Studenti studenti, String status, Date deadline) {
       this.id = id;
       this.teme = teme;
       this.studenti = studenti;
       this.status = status;
       this.deadline = deadline;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="tema", column=@Column(name="tema", nullable=false) ), 
        @AttributeOverride(name="nrmatr", column=@Column(name="nrmatr", nullable=false) ) } )
    public TmStudentId getId() {
        return this.id;
    }
    
    public void setId(TmStudentId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tema", nullable=false, insertable=false, updatable=false)
    public Teme getTeme() {
        return this.teme;
    }
    
    public void setTeme(Teme teme) {
        this.teme = teme;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="nrmatr", nullable=false, insertable=false, updatable=false)
    public Studenti getStudenti() {
        return this.studenti;
    }
    
    public void setStudenti(Studenti studenti) {
        this.studenti = studenti;
    }
    
    @Column(name="status", nullable=false, length=6)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="deadline", length=19)
    public Date getDeadline() {
        return this.deadline;
    }
    
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }




}


