package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ContracteStudiu generated by hbm2java
 */
@Entity
@Table(name = "contracte_studiu")
public class ContracteStudiu implements java.io.Serializable {

	private ContracteStudiuId id;
	private Studenti studenti;
	private CurCourse curCourse;
	private Float nota;
	private Date date;

	public ContracteStudiu() {
	}

	public ContracteStudiu(ContracteStudiuId id, Studenti studenti,
			CurCourse curCourse) {
		this.id = id;
		this.studenti = studenti;
		this.curCourse = curCourse;
	}

	public ContracteStudiu(ContracteStudiuId id, Studenti studenti,
			CurCourse curCourse, Float nota, Date date) {
		this.id = id;
		this.studenti = studenti;
		this.curCourse = curCourse;
		this.nota = nota;
		this.date = date;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "nrmat", column = @Column(name = "nrmat", nullable = false)),
			@AttributeOverride(name = "idCurs", column = @Column(name = "id_curs", nullable = false)),
			@AttributeOverride(name = "contractVersion", column = @Column(name = "contract_version", nullable = false)) })
	public ContracteStudiuId getId() {
		return this.id;
	}

	public void setId(ContracteStudiuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nrmat", nullable = false, insertable = false, updatable = false)
	public Studenti getStudenti() {
		return this.studenti;
	}

	public void setStudenti(Studenti studenti) {
		this.studenti = studenti;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_curs", nullable = false, insertable = false, updatable = false)
	public CurCourse getCurCourse() {
		return this.curCourse;
	}

	public void setCurCourse(CurCourse curCourse) {
		this.curCourse = curCourse;
	}

	@Column(name = "nota", precision = 12, scale = 0)
	public Float getNota() {
		return this.nota;
	}

	public void setNota(Float nota) {
		this.nota = nota;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
