package pcol.server.domain;

// Generated May 16, 2011 4:19:35 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Curicul generated by hbm2java
 */
@Entity
@Table(name = "curicul", catalog = "proj_col")
public class Curicul implements java.io.Serializable {

	private Integer id;
	private CurCourse curCourse;
	private OrgSection orgSection;
	private Integer optionalGroup;
	private int tip;
	private int ncredite;
	private int semester;
	private int an;
	private Set<ContracteStudiu> contracteStudius = new HashSet<ContracteStudiu>(
			0);

	public Curicul() {
	}

	public Curicul(CurCourse curCourse, OrgSection orgSection, int tip,
			int ncredite, int semester, int an) {
		this.curCourse = curCourse;
		this.orgSection = orgSection;
		this.tip = tip;
		this.ncredite = ncredite;
		this.semester = semester;
		this.an = an;
	}

	public Curicul(CurCourse curCourse, OrgSection orgSection,
			Integer optionalGroup, int tip, int ncredite, int semester, int an,
			Set<ContracteStudiu> contracteStudius) {
		this.curCourse = curCourse;
		this.orgSection = orgSection;
		this.optionalGroup = optionalGroup;
		this.tip = tip;
		this.ncredite = ncredite;
		this.semester = semester;
		this.an = an;
		this.contracteStudius = contracteStudius;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "courseId", nullable = false)
	public CurCourse getCurCourse() {
		return this.curCourse;
	}

	public void setCurCourse(CurCourse curCourse) {
		this.curCourse = curCourse;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sectieId", nullable = false)
	public OrgSection getOrgSection() {
		return this.orgSection;
	}

	public void setOrgSection(OrgSection orgSection) {
		this.orgSection = orgSection;
	}

	@Column(name = "optionalGroup")
	public Integer getOptionalGroup() {
		return this.optionalGroup;
	}

	public void setOptionalGroup(Integer optionalGroup) {
		this.optionalGroup = optionalGroup;
	}

	@Column(name = "tip", nullable = false)
	public int getTip() {
		return this.tip;
	}

	public void setTip(int tip) {
		this.tip = tip;
	}

	@Column(name = "ncredite", nullable = false)
	public int getNcredite() {
		return this.ncredite;
	}

	public void setNcredite(int ncredite) {
		this.ncredite = ncredite;
	}

	@Column(name = "semester", nullable = false)
	public int getSemester() {
		return this.semester;
	}

	public void setSemester(int semester) {
		this.semester = semester;
	}

	@Column(name = "an", nullable = false)
	public int getAn() {
		return this.an;
	}

	public void setAn(int an) {
		this.an = an;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "curicul")
	public Set<ContracteStudiu> getContracteStudius() {
		return this.contracteStudius;
	}

	public void setContracteStudius(Set<ContracteStudiu> contracteStudius) {
		this.contracteStudius = contracteStudius;
	}

}
