package pcol.server.domain;
// Generated Apr 15, 2011 12:35:22 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Cursuri generated by hbm2java
 */
@Entity
@Table(name="cursuri"
    ,catalog="proj_col"
)
public class Cursuri  implements java.io.Serializable {


     private Integer id;
     private int version;
     private Resurse resurse;
     private String nume;
     private String abreviere;
     private Set<Curicule> curicules = new HashSet<Curicule>(0);
     private Set<ContracteStudiu> contracteStudius = new HashSet<ContracteStudiu>(0);
     private Set<Teme> temes = new HashSet<Teme>(0);
     private Set<Orar> orars = new HashSet<Orar>(0);

    public Cursuri() {
    }

	
    public Cursuri(String nume, String abreviere) {
        this.nume = nume;
        this.abreviere = abreviere;
    }
    public Cursuri(Resurse resurse, String nume, String abreviere, Set<Curicule> curicules, Set<ContracteStudiu> contracteStudius, Set<Teme> temes, Set<Orar> orars) {
       this.resurse = resurse;
       this.nume = nume;
       this.abreviere = abreviere;
       this.curicules = curicules;
       this.contracteStudius = contracteStudius;
       this.temes = temes;
       this.orars = orars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="main_page")
    public Resurse getResurse() {
        return this.resurse;
    }
    
    public void setResurse(Resurse resurse) {
        this.resurse = resurse;
    }
    
    @Column(name="nume", nullable=false)
    public String getNume() {
        return this.nume;
    }
    
    public void setNume(String nume) {
        this.nume = nume;
    }
    
    @Column(name="abreviere", nullable=false, length=12)
    public String getAbreviere() {
        return this.abreviere;
    }
    
    public void setAbreviere(String abreviere) {
        this.abreviere = abreviere;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cursuri")
    public Set<Curicule> getCuricules() {
        return this.curicules;
    }
    
    public void setCuricules(Set<Curicule> curicules) {
        this.curicules = curicules;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cursuri")
    public Set<ContracteStudiu> getContracteStudius() {
        return this.contracteStudius;
    }
    
    public void setContracteStudius(Set<ContracteStudiu> contracteStudius) {
        this.contracteStudius = contracteStudius;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cursuri")
    public Set<Teme> getTemes() {
        return this.temes;
    }
    
    public void setTemes(Set<Teme> temes) {
        this.temes = temes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="cursuri")
    public Set<Orar> getOrars() {
        return this.orars;
    }
    
    public void setOrars(Set<Orar> orars) {
        this.orars = orars;
    }




}


