package pcol.server.domain;
// Generated Apr 14, 2011 10:54:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Mesaje generated by hbm2java
 */
@Entity
@Table(name="mesaje"
    ,catalog="proj_col"
)
public class Mesaje  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String msg;
     private Set<Canale> canales = new HashSet<Canale>(0);

    public Mesaje() {
    }

	
    public Mesaje(Users users, String msg) {
        this.users = users;
        this.msg = msg;
    }
    public Mesaje(Users users, String msg, Set<Canale> canales) {
       this.users = users;
       this.msg = msg;
       this.canales = canales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="expeditor", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="msg", nullable=false, length=65535)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="msg_chan", catalog="proj_col", joinColumns = { 
        @JoinColumn(name="msgid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="chanid", nullable=false, updatable=false) })
    public Set<Canale> getCanales() {
        return this.canales;
    }
    
    public void setCanales(Set<Canale> canales) {
        this.canales = canales;
    }




}


