package pcol.server.domain;
// Generated Apr 15, 2011 12:35:22 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Mesaje generated by hbm2java
 */
@Entity
@Table(name="mesaje"
    ,catalog="proj_col"
)
public class Mesaje  implements java.io.Serializable {


     private Integer id;
     private Users users;
     private String msg;
     private String level;
     private Date date;
     private Set<Canale> canales = new HashSet<Canale>(0);

    public Mesaje() {
    }

	
    public Mesaje(Users users, String msg, String level, Date date) {
        this.users = users;
        this.msg = msg;
        this.level = level;
        this.date = date;
    }
    public Mesaje(Users users, String msg, String level, Date date, Set<Canale> canales) {
       this.users = users;
       this.msg = msg;
       this.level = level;
       this.date = date;
       this.canales = canales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="expeditor", nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    
    @Column(name="msg", nullable=false, length=65535)
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    
    @Column(name="level", nullable=false, length=10)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date", nullable=false, length=19)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="msg_chan", catalog="proj_col", joinColumns = { 
        @JoinColumn(name="msgid", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="chanid", nullable=false, updatable=false) })
    public Set<Canale> getCanales() {
        return this.canales;
    }
    
    public void setCanales(Set<Canale> canales) {
        this.canales = canales;
    }




}


