package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * OrgGroup generated by hbm2java
 */
@Entity
@Table(name = "org_group", catalog = "proj_col")
public class OrgGroup implements java.io.Serializable {

	private String id;
	private OrgSection orgSection;
	private Set<Studenti> studentis = new HashSet<Studenti>(0);
	private List<Orar> orars = new ArrayList<Orar>(0);

	public OrgGroup() {
	}

	public OrgGroup(String id, OrgSection orgSection) {
		this.id = id;
		this.orgSection = orgSection;
	}

	public OrgGroup(String id, OrgSection orgSection, Set<Studenti> studentis,
			List<Orar> orars) {
		this.id = id;
		this.orgSection = orgSection;
		this.studentis = studentis;
		this.orars = orars;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 5)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "section", nullable = false)
	public OrgSection getOrgSection() {
		return this.orgSection;
	}

	public void setOrgSection(OrgSection orgSection) {
		this.orgSection = orgSection;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgGroup")
	public Set<Studenti> getStudentis() {
		return this.studentis;
	}

	public void setStudentis(Set<Studenti> studentis) {
		this.studentis = studentis;
	}

	//vreau o ordine stabila 
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orgGroup")
	@OrderBy("id")
	public List<Orar> getOrars() {
		return this.orars;
	}

	public void setOrars(List<Orar> orars) {
		this.orars = orars;
	}

}
