package pcol.server.domain;

// Generated Apr 28, 2011 8:02:06 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profesori generated by hbm2java
 */
@Entity
@Table(name = "profesori", catalog = "proj_col")
public class Profesori implements java.io.Serializable {

	private Integer id;
	private Logins logins;
	private Set<CurCourse> curCourses = new HashSet<CurCourse>(0);

	public Profesori() {
	}

	public Profesori(Logins logins) {
		this.logins = logins;
	}

	public Profesori(Logins logins, Set<CurCourse> curCourses) {
		this.logins = logins;
		this.curCourses = curCourses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", nullable = false)
	public Logins getLogins() {
		return this.logins;
	}

	public void setLogins(Logins logins) {
		this.logins = logins;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "profesori")
	public Set<CurCourse> getCurCourses() {
		return this.curCourses;
	}

	public void setCurCourses(Set<CurCourse> curCourses) {
		this.curCourses = curCourses;
	}

}
