package pcol.server.domain;

// Generated Apr 17, 2011 10:03:09 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Studenti generated by hbm2java
 */
@Entity
@Table(name = "studenti", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Studenti implements java.io.Serializable {

	private Integer nrMatr;
	private int version;
	private Users users;
	private OrgGroup orgGroup;
	private Set<TmStudent> tmStudents = new HashSet<TmStudent>(0);
	private Set<ContracteStudiu> contracteStudius = new HashSet<ContracteStudiu>(
			0);

	public Studenti() {
	}

	public Studenti(Users users, OrgGroup orgGroup) {
		this.users = users;
		this.orgGroup = orgGroup;
	}

	public Studenti(Users users, OrgGroup orgGroup, Set<TmStudent> tmStudents,
			Set<ContracteStudiu> contracteStudius) {
		this.users = users;
		this.orgGroup = orgGroup;
		this.tmStudents = tmStudents;
		this.contracteStudius = contracteStudius;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nr_matr", unique = true, nullable = false)
	public Integer getNrMatr() {
		return this.nrMatr;
	}

	public void setNrMatr(Integer nrMatr) {
		this.nrMatr = nrMatr;
	}

	@Version
	@Column(name = "version", nullable = false)
	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", unique = true, nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "grupaId", nullable = false)
	public OrgGroup getOrgGroup() {
		return this.orgGroup;
	}

	public void setOrgGroup(OrgGroup orgGroup) {
		this.orgGroup = orgGroup;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studenti")
	public Set<TmStudent> getTmStudents() {
		return this.tmStudents;
	}

	public void setTmStudents(Set<TmStudent> tmStudents) {
		this.tmStudents = tmStudents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studenti")
	public Set<ContracteStudiu> getContracteStudius() {
		return this.contracteStudius;
	}

	public void setContracteStudius(Set<ContracteStudiu> contracteStudius) {
		this.contracteStudius = contracteStudius;
	}

}
