package pcol.server.domain;

// Generated May 15, 2011 7:09:00 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Studenti generated by hbm2java
 */
@Entity
@Table(name = "studenti", catalog = "proj_col", uniqueConstraints = @UniqueConstraint(columnNames = "login"))
public class Studenti implements java.io.Serializable {

	private Integer nrMatr;
	private Logins logins;
	private int inscrisInAn;
	private Set<OrgGroup> orgGroups = new HashSet<OrgGroup>(0);
	private Set<TmStudent> tmStudents = new HashSet<TmStudent>(0);
	private NotePartiale notePartiale;
	private Set<ContracteStudiu> contracteStudius = new HashSet<ContracteStudiu>(
			0);

	public Studenti() {
	}

	public Studenti(Logins logins, int inscrisInAn) {
		this.logins = logins;
		this.inscrisInAn = inscrisInAn;
	}

	public Studenti(Logins logins, int inscrisInAn, Set<OrgGroup> orgGroups,
			Set<TmStudent> tmStudents, NotePartiale notePartiale,
			Set<ContracteStudiu> contracteStudius) {
		this.logins = logins;
		this.inscrisInAn = inscrisInAn;
		this.orgGroups = orgGroups;
		this.tmStudents = tmStudents;
		this.notePartiale = notePartiale;
		this.contracteStudius = contracteStudius;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nr_matr", unique = true, nullable = false)
	public Integer getNrMatr() {
		return this.nrMatr;
	}

	public void setNrMatr(Integer nrMatr) {
		this.nrMatr = nrMatr;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "login", unique = true, nullable = false)
	public Logins getLogins() {
		return this.logins;
	}

	public void setLogins(Logins logins) {
		this.logins = logins;
	}

	@Column(name = "inscris_in_an", nullable = false)
	public int getInscrisInAn() {
		return this.inscrisInAn;
	}

	public void setInscrisInAn(int inscrisInAn) {
		this.inscrisInAn = inscrisInAn;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "studenti_grupe", catalog = "proj_col", joinColumns = { @JoinColumn(name = "nrmatr", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "groupid", nullable = false, updatable = false) })
	public Set<OrgGroup> getOrgGroups() {
		return this.orgGroups;
	}

	public void setOrgGroups(Set<OrgGroup> orgGroups) {
		this.orgGroups = orgGroups;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studenti")
	public Set<TmStudent> getTmStudents() {
		return this.tmStudents;
	}

	public void setTmStudents(Set<TmStudent> tmStudents) {
		this.tmStudents = tmStudents;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "studenti")
	public NotePartiale getNotePartiale() {
		return this.notePartiale;
	}

	public void setNotePartiale(NotePartiale notePartiale) {
		this.notePartiale = notePartiale;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studenti")
	public Set<ContracteStudiu> getContracteStudius() {
		return this.contracteStudius;
	}

	public void setContracteStudius(Set<ContracteStudiu> contracteStudius) {
		this.contracteStudius = contracteStudius;
	}

}
