package pcol.server.domain;
// Generated Apr 14, 2011 10:54:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * Studenti generated by hbm2java
 */
@Entity
@Table(name="studenti"
    ,catalog="proj_col"
    , uniqueConstraints = @UniqueConstraint(columnNames="login") 
)
public class Studenti  implements java.io.Serializable {


     private Integer nrMatr;
     private int version;
     private Users users;
     private Grupe grupe;
     private Set<Users> userses = new HashSet<Users>(0);
     private Set<TmStudent> tmStudents = new HashSet<TmStudent>(0);
     private Set<ContracteStudiu> contracteStudius = new HashSet<ContracteStudiu>(0);

    public Studenti() {
    }

	
    public Studenti(Users users, Grupe grupe) {
        this.users = users;
        this.grupe = grupe;
    }
    public Studenti(Users users, Grupe grupe, Set<Users> userses, Set<TmStudent> tmStudents, Set<ContracteStudiu> contracteStudius) {
       this.users = users;
       this.grupe = grupe;
       this.userses = userses;
       this.tmStudents = tmStudents;
       this.contracteStudius = contracteStudius;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="nr_matr", unique=true, nullable=false)
    public Integer getNrMatr() {
        return this.nrMatr;
    }
    
    public void setNrMatr(Integer nrMatr) {
        this.nrMatr = nrMatr;
    }
    @Version
    @Column(name="version", nullable=false)
    public int getVersion() {
        return this.version;
    }
    
    public void setVersion(int version) {
        this.version = version;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="login", unique=true, nullable=false)
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grupaId", nullable=false)
    public Grupe getGrupe() {
        return this.grupe;
    }
    
    public void setGrupe(Grupe grupe) {
        this.grupe = grupe;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studentis")
    public Set<Users> getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studenti")
    public Set<TmStudent> getTmStudents() {
        return this.tmStudents;
    }
    
    public void setTmStudents(Set<TmStudent> tmStudents) {
        this.tmStudents = tmStudents;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="studenti")
    public Set<ContracteStudiu> getContracteStudius() {
        return this.contracteStudius;
    }
    
    public void setContracteStudius(Set<ContracteStudiu> contracteStudius) {
        this.contracteStudius = contracteStudius;
    }




}


