package pcol.server.domain;
// Generated Apr 14, 2011 10:54:13 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teme generated by hbm2java
 */
@Entity
@Table(name="teme"
    ,catalog="proj_col"
)
public class Teme  implements java.io.Serializable {


     private int id;
     private Cursuri cursuri;
     private int cerintePage;
     private Set<TmStudent> tmStudents = new HashSet<TmStudent>(0);

    public Teme() {
    }

	
    public Teme(int id, Cursuri cursuri, int cerintePage) {
        this.id = id;
        this.cursuri = cursuri;
        this.cerintePage = cerintePage;
    }
    public Teme(int id, Cursuri cursuri, int cerintePage, Set<TmStudent> tmStudents) {
       this.id = id;
       this.cursuri = cursuri;
       this.cerintePage = cerintePage;
       this.tmStudents = tmStudents;
    }
   
     @Id 
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="curs", nullable=false)
    public Cursuri getCursuri() {
        return this.cursuri;
    }
    
    public void setCursuri(Cursuri cursuri) {
        this.cursuri = cursuri;
    }
    
    @Column(name="cerinte_page", nullable=false)
    public int getCerintePage() {
        return this.cerintePage;
    }
    
    public void setCerintePage(int cerintePage) {
        this.cerintePage = cerintePage;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="teme")
    public Set<TmStudent> getTmStudents() {
        return this.tmStudents;
    }
    
    public void setTmStudents(Set<TmStudent> tmStudents) {
        this.tmStudents = tmStudents;
    }




}


