package pcol.server.domain;

// Generated Apr 28, 2011 8:02:06 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TmStudentId generated by hbm2java
 */
@Embeddable
public class TmStudentId implements java.io.Serializable {

	private int temaId;
	private int nrmatr;

	public TmStudentId() {
	}

	public TmStudentId(int temaId, int nrmatr) {
		this.temaId = temaId;
		this.nrmatr = nrmatr;
	}

	@Column(name = "temaId", nullable = false)
	public int getTemaId() {
		return this.temaId;
	}

	public void setTemaId(int temaId) {
		this.temaId = temaId;
	}

	@Column(name = "nrmatr", nullable = false)
	public int getNrmatr() {
		return this.nrmatr;
	}

	public void setNrmatr(int nrmatr) {
		this.nrmatr = nrmatr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TmStudentId))
			return false;
		TmStudentId castOther = (TmStudentId) other;

		return (this.getTemaId() == castOther.getTemaId())
				&& (this.getNrmatr() == castOther.getNrmatr());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTemaId();
		result = 37 * result + this.getNrmatr();
		return result;
	}

}
