package pcol.server.domain;
// Generated Apr 15, 2011 12:35:22 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="proj_col"
)
public class Users  implements java.io.Serializable {


     private String loginName;
     private Persoane persoane;
     private String passwordHash;
     private String salt;
     private String lastlogin;
     private String lastip;
     private Set<Mesaje> mesajes = new HashSet<Mesaje>(0);
     private Set<Canale> canales = new HashSet<Canale>(0);
     private Set<Studenti> studentis = new HashSet<Studenti>(0);

    public Users() {
    }

	
    public Users(String loginName, String passwordHash, String salt) {
        this.loginName = loginName;
        this.passwordHash = passwordHash;
        this.salt = salt;
    }
    public Users(String loginName, Persoane persoane, String passwordHash, String salt, String lastlogin, String lastip, Set<Mesaje> mesajes, Set<Canale> canales, Set<Studenti> studentis) {
       this.loginName = loginName;
       this.persoane = persoane;
       this.passwordHash = passwordHash;
       this.salt = salt;
       this.lastlogin = lastlogin;
       this.lastip = lastip;
       this.mesajes = mesajes;
       this.canales = canales;
       this.studentis = studentis;
    }
   
     @Id 
    
    @Column(name="login_name", unique=true, nullable=false, length=45)
    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="persoana")
    public Persoane getPersoane() {
        return this.persoane;
    }
    
    public void setPersoane(Persoane persoane) {
        this.persoane = persoane;
    }
    
    @Column(name="password_hash", nullable=false, length=45)
    public String getPasswordHash() {
        return this.passwordHash;
    }
    
    public void setPasswordHash(String passwordHash) {
        this.passwordHash = passwordHash;
    }
    
    @Column(name="salt", nullable=false, length=45)
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    
    @Column(name="lastlogin", length=45)
    public String getLastlogin() {
        return this.lastlogin;
    }
    
    public void setLastlogin(String lastlogin) {
        this.lastlogin = lastlogin;
    }
    
    @Column(name="lastip", length=45)
    public String getLastip() {
        return this.lastip;
    }
    
    public void setLastip(String lastip) {
        this.lastip = lastip;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Mesaje> getMesajes() {
        return this.mesajes;
    }
    
    public void setMesajes(Set<Mesaje> mesajes) {
        this.mesajes = mesajes;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="subscriptii", catalog="proj_col", joinColumns = { 
        @JoinColumn(name="login", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="id_canal", nullable=false, updatable=false) })
    public Set<Canale> getCanales() {
        return this.canales;
    }
    
    public void setCanales(Set<Canale> canales) {
        this.canales = canales;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="users")
    public Set<Studenti> getStudentis() {
        return this.studentis;
    }
    
    public void setStudentis(Set<Studenti> studentis) {
        this.studentis = studentis;
    }




}


